* Introduction
I love sudoku.  I think it's the best type of puzzle because of the wild conclusions you
can make from only using a little logical deduction.  I like them more than crosswords,
mainly because I don't have to remember what an "ewe" is or who won a tony award in 
1992.  

Sudoku is also fun because you can brute force the puzzles with computers.  Solving a 
difficult puzzle without any help is fun but it's also really fun to write a program
to do it for you.  And that is exactly what we'll do here today. 

I'll be recreating a project that I did in a summer class I took at Harvard.  Since it 
was a very compressed Java class, most of the code was written for us.  Though we did
have to write the meat of it ourselves.  I'd like to rework the original and reimplement
the code into C.  The original Java code relied heavily on classes and methods, so it'll
be interesting to see how it ends up working in C.

When I first did this, I remember it took me about two days to figure out what was really
going on.  I spent hours just moving different variables around to see what would happnen.
Eventually, I stumbled on the right answer and it all suddenly made sense.  Hopefully this article will
not only be interesting, but also provide a decent explanation for understanding recursive backtracking.  
